name: main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge

      - name: Install dependencies
        run: conda install --file ci/conda_requirements.txt 

      - name: Install CI packages
        run: conda install pycodestyle coverage ruff

      - name: Install program
        run: pip install -e .

      - name: Ruff
        run: |
          pip install ruff
          ruff check .
          ruff fix .
